#!/usr/bin/env bash
# Shows information about subdomain

domain_information() {
    local domain="$1"
    local subdomain="$2"
    local line
    line=$(dig +short "$subdomain"."$domain")

    if [ -z "$line" ]; then
        echo "Unable to retrieve information for $subdomain.$domain"
    else
        local record_type
        local points_to

        record_type=$(dig "$subdomain"."$domain" | awk '/ANSWER SECTION:/ {getline; print $4}')
        points_to=$(echo "$line" | head -n 1)

        echo "The subdomain $subdomain is a $record_type record and points to $points_to"
    fi
}

if [ "$#" -eq 1 ]; then
    domain_information "$1" "www"
    domain_information "$1" "lb-01"
    domain_information "$1" "web-01"
    domain_information "$1" "web-02"
elif [ "$#" -eq 2 ]; then
    domain_information "$1" "$2"
fi

